name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN_SET: ${{ secrets.CODECOV_TOKEN != '' && secrets.CODECOV_TOKEN != null }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run linting
      if: matrix.python-version == '3.11'
      run: |
        flake8 wikipedia_mcp tests
        black --check wikipedia_mcp tests
        mypy wikipedia_mcp

    - name: Run tests
      run: |
        pytest --cov=wikipedia_mcp tests/ -v --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      if: ${{ matrix.python-version == '3.11' && env.CODECOV_TOKEN_SET == 'true' }}
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}

  build-test:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build
        ls -la dist/

    - name: Check package
      run: |
        twine check dist/*

    - name: Test installation
      run: |
        pip install dist/*.whl
        wikipedia-mcp --help
